### PR TITLE
New speedseq freeze version using Samblaster 0.1.22 

### PR DESCRIPTION
**Pull request by susannasiebert**

### CODE REVIEW

**Comment by tmooney** [comment]
+1.  Are the new `.bam` files something that this new version produces that the old one did not?

**Comment by susannasiebert** [comment]
The `.bam` files now contain supplementary reads.

**Comment by apregier** [comment]
+1 Do you have new processing profiles already?

**Comment by susannasiebert** [comment]
I haven't made new processing profiles yet.

**Pull request merged**
