### PR TITLE
Iterate through ldapsearch output

### PR DESCRIPTION
**Pull request by dufeiyu**
Currently 1000 is used as response size limit for ldapsearch.  Modify this so more info can be obtained.

### CODE REVIEW

**Comment by brummett** [comment]
Since this may return a considerable amount of data, it may be worth switching to an iterator-based read from ldapsearch rather than slurping everything up with ```my @c = `ldapsearch -z 0 -x`;```

**Comment by dufeiyu** [comment]
Good point. I will make the change.

**Comment by ebelter** [comment]
@brummett @tmooney Has anyone used Net::LDAP->search ?

**Comment by brummett** [comment]
I haven't used Net::LDAP.  It seems to have a decent set of tests and one of the contributors (gbarr) has a few modules in the Perl standard library.  I'd say it's worth trying out, though the debian package we have available is pretty old.

**Comment by brummett** [comment]
I can't figure out how to use Net::LDAP.  trying to find all the user records with ```$ldap->search('(objectClass=person)')``` or entries with email addresses (as this function seems to be doing) with ```$ldap->search('(email=*)')``` always return 0 records.  I guess it's either not working or I don't know what I'm doing...  Though Net::LDAP would be better than the janky parsing this function is using.

+1, this change improves the existing function.

**Comment by ebelter** [comment]
I believe we are switching to FreeIPA. Not sure how that will affect this.

**Comment by ebelter** [comment]
Talking to Rob F about using Net::LDAP.

**Comment by dufeiyu** [comment]
@ebelter Eddie agrees to push this for now to fix current problem. Future PR can be created for the new change.

**Comment by ebelter** [comment]
I will have a PR using et::LDAP from an example @rfugina provided.

**Pull request merged**
