### PR TITLE
Remove "ContaminationScreen" GMT tree.

### PR DESCRIPTION
**Pull request by tmooney**
This is another case of deletion as the alternative to updating to `WorkflowBuilder`.

(No recorded uses of this were found in the entirety of the usage log.)

### CODE REVIEW

**Comment by jeldred** [comment]
bitmoji

**Comment by tmooney** [comment]
Is that a "+1"?

**Comment by jeldred** [comment]
:+1: :shipit:

**Comment by ebelter** [comment]
+1 :light_rail:

**Pull request merged**
