### PR TITLE
Disconnect Database Handles before potentially long-running actions

### PR DESCRIPTION
**Pull request by tmooney**
The specific motivation for this change: The database "pausing" feature will disconnect handles, but not if the pause is both set and cleared before the program has a chance to notice.  It may then be left holding a stale handle when it does return.

### CODE REVIEW

**Comment by brummett** [comment]
+1

**Comment by apregier** [comment]
In Genome::WorkflowBuilder::DAG, why do we need to disconnect the db handles in _execute_with_workflow but not _execute_with_ptero?

**Comment by tmooney** [comment]
@apregier Good question!  I've added a disconnect before we wait on PTero now as well.

**Comment by acoffman** [comment]
+1

**Comment by apregier** [comment]
+1

**Pull request merged**
