### PR TITLE
Instrument Data Command Cleanup

### PR DESCRIPTION
**Pull request by ebelter**
Removed a couple of comands and instdata properties from the command tree.

### CODE REVIEW

**Comment by tmooney** [comment]
+1, it'd be nice to have a `CHANGELOG` entry for this pointing to the command that will still be around.

**Comment by dufeiyu** [comment]
+1 for removing unused codes

**Comment by ebelter** [comment]
@tmooney Should I add the CHANGELOG to the merge commit, or do I need to amend and force push/push another commit tot he branch?

**Comment by tmooney** [comment]
@ebelter It's fine to add it to the merge commit.

**Comment by ebelter** [comment]
CHANGELOG: Removed Instrument Data Redundant Commands

ignored
Use auto-generated command: 'genome instrument-data update ignored --h'

est-library-complexity
This command works on instdata that have fastqs, which is no longer true. This makes this command unusable. Use the picard command directly with the instrument data 'bam_path' : 'gmt picard estimate-library-complexity --h'

**Pull request merged**
