### PR TITLE
New chr_md5 reference converter

### PR DESCRIPTION
**Pull request by jasonwalker80**
A new reference sequence converter that relies on matching the md5 in each build sequence dictionary to map chromosome names.

### CODE REVIEW

**Comment by jasonwalker80** [comment]
This replaces #1303

**Comment by jasonwalker80** [comment]
New commits to address suggestions.

**Comment by tmooney** [comment]
Looks like the bucket-creation tests are failing, because they used mocked-up seqdict files without the additional info we're now expecting.  But +1 once those are fixed!

I like the fact that this will fail unless the two references really are identical.  That does mean this implementation is not compatible with the existing `drop_extra_contigs` implementation.

**Comment by susannasiebert** [comment]
+1

**Pull request merged**
