### PR TITLE
improve error message when trying to rename across devices

### PR DESCRIPTION
**Pull request by nnutter**

### CODE REVIEW

**Comment by ebelter** [comment]
+1 Not sure why anyone would use rename vs. File::Copy::move but this gives a great error.

**Comment by nnutter** [comment]
You would use `rename` when you needed to ensure an atomic operation.  `File::Copy::move` falls back to a copy and delete when a rename isn't possible (which is usually when the move is cross device).

**Comment by ebelter** [comment]
File::Copy::move tries rename first.

**Comment by nnutter** [comment]
And falls back on a non-atomic operation.

**Comment by tmooney** [comment]
+1 :cherry_blossom:

**Pull request merged**
