### PR TITLE
Remove TestPipeline model type

### PR DESCRIPTION
**Pull request by ebelter**
This model-type produced state-of-the-art something or other. Actually, it was more about documenting the creation of a new pipeline. And its time has long passed.

Prior to merging, all of these useless models, builds, and processing profiles will be removed.

### CODE REVIEW

**Comment by tmooney** [comment]
I'm not sure this warrants a `CHANGELOG` entry.  (Has any user heard of or considered this pipeline for anything?)

**Comment by ebelter** [comment]
I do not care if it has a change log or not.

**Comment by acoffman** [comment]
+1

**Comment by tmooney** [comment]
+1 :fire:

**Comment by ebelter** [comment]
Database clean up complete, merging.

**Pull request merged**
