### PR TITLE
Deprecated AnP status Timeline event.

### PR DESCRIPTION
**Pull request by jasonwalker80**
Add valid_value for Deprecated AnP status.

### CODE REVIEW

**Comment by tmooney** [comment]
+1.  Should `Template` be added as well?

**Comment by jasonwalker80** [comment]
I'm not sure.  The timeline events are for when the status is changed.  With Template, it's either created with --store-only or it's not.  I don't think changing status too or from Template would be desired.  I'm open to other ideas or opinions though.

**Comment by tmooney** [comment]
I believe it will try to store the status when noting changes to `is_cle` or `run_as` as well. (None of these are likely to be changed for `Template`s either.)

Maybe instead of adding it explicitly we could use `Genome::Config::AnalysisProject->__meta__->property(property_name => 'status')->valid_values` so the lists always match.

Or this is fine as is!

**Comment by jasonwalker80** [comment]
I like the suggestion @tmooney.  New commit to use all valid_values from AnPs to avoid duplication.

**Comment by acoffman** [comment]
+1

**Pull request merged**
