### PR TITLE
Sync Sys/LDAP Users: Add --max-changes-allowed option to run with more than 10 changes

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by tmooney** [comment]
I have been advocating against naming parameters `--force`.  Perhaps this could be an integer parameter like `--max-allowed-changes` with default of `10`?  Or if we stick with a boolean, maybe `--allow-copious-changes` or something descriptive like that?

**Comment by ebelter** [comment]
@tmooney Sure...done.

**Comment by acoffman** [comment]
+1

**Comment by tmooney** [comment]
+1 :banana:

**Pull request merged**
