### PR TITLE
Add experimental support for instrument data with tar.gz of FASTQs.

### PR DESCRIPTION
**Pull request by tmooney**
This is untested so far.

### CODE REVIEW

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by chrisamiller** [comment]
+1 
Tested and seems to work on a large-ish set of samples (~500, mixed between old archives and new)

**Comment by chrisamiller** [comment]
Added one additional fix that handles empty md5 files, which regrettably seem to exist for some old data 😦

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by chrisamiller** [comment]
I used this successfully on a whole bunch of files and think it could be merged after someone review my last fix

**Comment by tmooney** [comment]
+1 to your fix!  I'll merge this so it has a chance to be in a snapshot before this archive system goes away :smile:

**Pull request merged**
