### PR TITLE
More build restart fixes

### PR DESCRIPTION
**Pull request by tmooney**
Inspired by #1826.

The one downside of this approach is old builds/processes won't be able to display their workflows anymore, since the name doesn't match. Alternatives might include storing the name in the database or adding some date logic to decide which name to generate... but those are a lot more complex solutions to the problem.

### CODE REVIEW

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by chrisamiller** [comment]
Just tried restarting a build and it seemed to do the right thing. Will update with success/failure after it's done

```
$ genome-perl -I /gscmnt/gc2761/aml_ppg/tmp/genome_more_build_restart_fixes/lib/perl/ `which genome` model cwl-pipeline restart --builds=d18cd9da9b934afebcf
34daa9c30913b
'builds' may require verification...
Resolving parameter 'builds' from command argument 'd18cd9da9b934afebcf34daa9c30913b'... found 1
DEBUG: Attempting to create a disk_allocation for process (e30c86e2ffa04e6c9988e330506544d8) with arguments: {
  allocation_path     => "model_data/process/e30c86e2ffa04e6c9988e330506544d8",
  disk_group_name     => "aml_ppg_gms",
  kilobytes_requested => 51200,
  owner_class_name    => "Genome::Model::Build::Process",
  owner_id            => "e30c86e2ffa04e6c9988e330506544d8",
}
DEBUG: Allocation (1bb9d71a831f4a8c88093d2944cb139e) created at /gscmnt/gc2761/aml_ppg/model_data/process/e30c86e2ffa04e6c9988e330506544d8
Process (e30c86e2ffa04e6c9988e330506544d8) now has disk_allocation (1bb9d71a831f4a8c88093d2944cb139e)
DEBUG: Created closure to delete disk allocation (1bb9d71a831f4a8c88093d2944cb139e) associated with process (e30c86e2ffa04e6c9988e330506544d8)
Reading in workflow from file: /gscmnt/gc2761/aml_ppg/model_data/process/e30c86e2ffa04e6c9988e330506544d8/workflow.xml
Submitting workflow with inputs: {
  build => bless({
        __get_serial      => 5572,
        __load            => {
                               "Genome::Model::Build/And/build_id,id,subclass_name/O:"              => {
                                                                                                         "Genome::Model::Build/And/build_id,id,subclass_name/O:\35O:d18cd9da9b934af
ebcf34daa9c30913b\36d18cd9da9b934afebcf34daa9c30913b\36Genome::Model::Build::CwlPipeline\36"              => undef,
                                                                                                         "Genome::Model::Build::CwlPipeline/And/build_id,id,subclass_name/O:\35O:d1
8cd9da9b934afebcf34daa9c30913b\36d18cd9da9b934afebcf34daa9c30913b\36Genome::Model::Build::CwlPipeline\36" => 1,
                                                                                                       },
                               "Genome::Model::Build::CwlPipeline/And/build_id,id,subclass_name/O:" => {
                                                                                                                                      },                                                                                                         "Genome::Model::Build::CwlPipeline/And/build_id,id,subclass_name/O:\35O:d18cd9da9b934afebcf34daa9c30913b\36d18cd9da9b934afebcf34daa9c30913b\36Genome::Model::Build::CwlPipeline\36" => 1,
                                                                                                       },
                             },
        _change_count     => 4,
        build_id          => "d18cd9da9b934afebcf34daa9c30913b",
        created_at        => "2018-02-15 12:35:10",
        created_by        => "prod-builder",
        data_directory    => "/gscmnt/gc2761/aml_ppg/model_data/5359f94590354ffa94229f9e3301beff/buildd18cd9da9b934afebcf34daa9c30913b",
        date_completed    => undef,
        date_scheduled    => "2018-02-15 12:35:16",
        db_committed      => {
                               build_id          => "d18cd9da9b934afebcf34daa9c30913b",
                               created_at        => "2018-02-15 12:35:10",
                               created_by        => "prod-builder",
                               data_directory    => "/gscmnt/gc2761/aml_ppg/model_data/5359f94590354ffa94229f9e3301beff/buildd18cd9da9b934afebcf34daa9c30913b",
                               date_completed    => "2018-02-18 12:52:35",
                               date_scheduled    => "2018-02-15 12:35:16",
                               model_id          => "5359f94590354ffa94229f9e3301beff",
                               run_by            => "prod-builder",
                               software_revision => "/gsc/scripts/opt/genome/snapshots/genome-3766/lib/perl/Genome/Site/TGI/SiteLib:/gsc/scripts/opt/genome/snapshots/genome-3766/lib/perl:/etc/perl:/usr/local/lib/site_perl",
                               status            => "Failed",
                               subclass_name     => "Genome::Model::Build::CwlPipeline",
                               updated_at        => "2018-02-18 13:16:43",
                             },
        id                => "d18cd9da9b934afebcf34daa9c30913b",
        model_id          => "5359f94590354ffa94229f9e3301beff",
        run_by            => "prod-builder",
        software_revision => "/gsc/scripts/opt/genome/snapshots/genome-3766/lib/perl/Genome/Site/TGI/SiteLib:/gsc/scripts/opt/genome/snapshots/genome-3766/lib/perl:/etc/perl:/usr/local/lib/site_perl",
        status            => "Scheduled",
        subclass_name     => "Genome::Model::Build::CwlPipeline",
        updated_at        => "2018-02-18 14:21:32",
      }, "Genome::Model::Build::CwlPipeline"),
}
Build (d18cd9da9b934afebcf34daa9c30913b of H_KA-613389-M1500081_1.prod-cwl) restarted. An initialization email will be sent once the build begins running.
Submitted workflow to petri service: http://workflow.apipe-deis.gsc.wustl.edu:80/v1/workflows/1430409
Successfully launched process (e30c86e2ffa04e6c9988e330506544d8) and¯ submitted PTero workflow (http://workflow.apipe-deis.gsc.wustl.edu:80/v1/workflows/1430409)
```

**Pull request merged**
