### PR TITLE
Remove Blat GMT Tree and Alignment Result

### PR DESCRIPTION
**Pull request by tmooney**
Another use of `Workflow` gone...

### CODE REVIEW

**Comment by jasonwalker80** [comment]
+1.  Is blat used anywhere in the GMS?  Is this a candidate for removal rather than updating to WorkflowBuilder?

**Comment by tmooney** [comment]
There's an `AlignmentResult` class for Blat still.  It is quite possibly a candidate for removal otherwise.

**Comment by jasonwalker80** [comment]
My opinion, I would check for any recent (<1 year old) results and remove the AlignmentResult class if it's no longer used.

**Comment by tmooney** [comment]
The AlignmentResult class was used exactly thrice ever.  I've updated this PR to remove the Blat tools completely.

**Comment by jasonwalker80** [comment]
+1

**Comment by jeldred** [comment]
+1

**Pull request merged**
