### PR TITLE
InstData Import: update sra to bam for the fixed version of sam-dump. YAY!

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by ebelter** [comment]
This PR will remain open until we repackage (by @iferguson90) the sra-sdk with the new version of sra tool kit.

**Comment by tmooney** [comment]
:guitar: +1, this really simplifies things!

**Comment by acoffman** [comment]
+1 :space_invader:  *43 additions and 258 deletions*  :space_invader:

**Comment by iferguson90** [comment]
+1

So, I opened genome/genome-snapshot-deps#11 for sra-toolkit 2.4.3, but it looks like Puppet decided to update all the workstations and blades to 2.4.3 anyways.

According to @mkiwala, @brummett, and @nnutter, 2.4.3 is causing test failures because `sra-dbcc` is no longer present. This PR removes one of the uses of `sra-dbcc`. A `grep` through Genome suggests that the other use is in `Genome/InstrumentData/Command/Export/Samplesheet.pm`, line 666, under a sub named `_transfer_sra_source_file`. Do you know anything about this, @ebelter?

**Comment by ebelter** [comment]
CI, test this

**Pull request merged**
