### PR TITLE
Remove GMTs that relied on Workflow integration.

### PR DESCRIPTION
**Pull request by tmooney**
These used a `Workflow`-specific way of parallel_by that effectively made them workflows unto themselves.  The underlying commands are still around for use if needed for now.

### CODE REVIEW

**Comment by wschroeder** [comment]
I have been advocating for us leveraging Ptero over the Workflow stuff, but I am concerned about removing tests for existing packages that may warrant future maintenance.  Should we delete the tools as well?  Is someone going to replace the tests with more modern tests?

**Comment by tmooney** [comment]
@wschroeder I'd be happy to delete more tools!  (or write new tests as needed :smile:) I'm not sure which tests you're concerned about, though.

**Comment by wschroeder** [comment]
That's because I didn't check all the package names there.  How silly!  Ignore my comment.  Instead:

+1 🎃

**Comment by acoffman** [comment]
+1

**Pull request merged**
