### PR TITLE
Update annotation builds to some that exist.

### PR DESCRIPTION
**Pull request by tmooney**
I accidentally deleted a few annotation build directories that were in use by these tests.  This updates the test to use others that still exist. 😄 

I'm not keen on the hard-coded path, but this maintains the status quo.

### CODE REVIEW

**Comment by susannasiebert** [comment]
How difficult would it be to switch to a version using mock objects?

**Comment by tmooney** [comment]
It turned out to be easy enough to extract the files needed for the Chimerascan index test, which was using a fake annotation build but real data previously.

The other test is using a lot more of a real annotation build.  I'm not sure if it's a good idea to copy so much of it or if it falls under the "well-known data" exception in some way.  We could convert it to ask for the annotation build by name and version instead of by build ID...

**Comment by susannasiebert** [comment]
+1

**Comment by jeldred** [comment]
:+1: ⚽

**Pull request merged**
