### PR TITLE
adding option to stop clustering in 1d

### PR DESCRIPTION
**Pull request by chrisamiller**

### CODE REVIEW

**Comment by apregier** [comment]
+1

**Comment by nnutter** [comment]
Test failure is probably due to high load.  Will re-run once things calm down.

**Comment by acoffman** [comment]
+1 once tests pass. As a note, I think if you supply a default value, you don't need `is_optional`. If the user doesn't pass in a value, the default will be used.

**Comment by chrisamiller** [comment]
Removed is_optional, as suggested.  Merging.

**Pull request merged**
