### PR TITLE
Updating SraToBam.pm to use new input params. 

### PR DESCRIPTION
**Pull request by dummey**

### CODE REVIEW

**Comment by apipe-tester** [comment]
Can one of the admins verify this patch?

**Comment by nnutter** [comment]
CI, test this once.

**Comment by nnutter** [comment]
@dummey, I'm assuming this crashed because of `$self->library`?  Should the doc string for `library_name` or `sample_name` be updated as well?  They both mention being used in the RG headers.  Otherwise, +1 if tests pass.

**Comment by tmooney** [comment]
+1

**Pull request merged**
