### PR TITLE
Inactivate AnP Config Files

### PR DESCRIPTION
**Pull request by jasonwalker80**
Initial revision of a command to inactivate config files.

### CODE REVIEW

**Comment by tmooney** [comment]
+1

It'd be nice to have a `.t` to go along with this.  (The test for `DisableConfigFile.pm` should work with minimal changes.)

**Comment by brummett** [comment]
I agree with needing a test.  It'll help in the future if this command gets additional functionality.

**Comment by jasonwalker80** [comment]
I agree with the need for a test case.  I'll look at the DisableConfigFile.t and see where I get.

**Comment by jasonwalker80** [comment]
Test added.

**Comment by brummett** [comment]
+1

**Pull request merged**
