### PR TITLE
De Novo Assembly: add number of threads to lsf resource when processing instrument data.

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by nnutter** [comment]
I'm skeptical that this works.  Have you tried running a build and seen that LSF gets the thread count?

**Comment by ebelter** [comment]
@tmooney indicated something of the like would work - maybe I implemented it incorrectly. I meant to run a build, but forgot. I will send one off and see what happens!.

**Comment by ebelter** [comment]
@nnutter @tmooney The inputs passed in have a build, but it is a 'Workflow::Link::Instance'. When calling 'value' on it, this error is encountered:
 ERROR: Can't call method "output" on an undefined value at /gsc/scripts/opt/genome/snapshots/genome-3588/lib/perl/Workflow/Link/Instance.pm line 49.

So it seems there is no operation instance for the link, even though it has an id.

**Comment by tmooney** [comment]
@ebelter This is a peculiarity of `Workflow`'s multi-process behaviour... The IDs referenced only refer to objects in the other process.  I think maybe [`$type->resource_for_instance(...)`](https://github.com/genome/tgi-workflow/blob/43813893069460826e8db143081219f33d07b8ba/lib/Workflow/Server/Hub.pm#L512) should use `$payload->{input}` instead of consulting `$instance->input`.

(I suppose it shouldn't be too surprising there are bugs in this feature, since we don't really use it... and it only [theoretically] works in the Workflow system we're moving away from.)

**Comment by ebelter** [comment]
@tmooney Perhaps a hard coded class selection based on threading when building  the workflow:

if threads
 Class::RunWithThreads
else
 Class::Run?

**Comment by tmooney** [comment]
That would work!

If you only ever need one resource requirement for a given OperationType, it might also work to override the resource requirements when constructing the workflow so it gets into the XML with the desired thread count.  (I know some past pipelines worked that way; I'm not sure if that still works.)

**Comment by ebelter** [comment]
@tmooney I took the approach you suggested. Thanks!

**Comment by tmooney** [comment]
+1 It worked when tested with `Workflow`! :dash:

**Pull request merged**
