### PR TITLE
Replace LockMigrationProxy with LockProxy

### PR DESCRIPTION
**Pull request by dufeiyu**
Change LockMigrationProxy back to LockProxy since the migration of lock resource from G::I::AR::Merged to G::I::AR is done.

### CODE REVIEW

**Comment by acoffman** [comment]
+1

**Comment by nnutter** [comment]
`genome-3591` and `genome-3592` are still running builds and are still using `Genome::InstrumentData::AlignmentResult::Merged`.  We should wait to merge this until those snapshots are [archived](https://apipe-ci.gsc.wustl.edu/view/Maintenance/job/Archive%20Stale%20Snapshots%20%28Maintenance%29/).

**Comment by dufeiyu** [comment]
ok

**Comment by dufeiyu** [comment]
CI, test this

**Comment by dufeiyu** [comment]
@nnutter there are 1 build using 3591 and 16 builds using 3592. 15 builds were idle/stalled due to system instability. I abandoned and requeued those 15 builds. 2 builds are running time-consuming cufflink that are only steps left for the builds and the merge steps of these 2 builds that use G::I::AR::Merged were done two weeks ago. It should be safe to merge this now.

**Comment by nnutter** [comment]
:+1: Seems safe enough to me.

**Pull request merged**
