### PR TITLE
Minor Improvements to BamWindow Wrapper

### PR DESCRIPTION
**Pull request by nnutter**
In trying to troubleshoot [RT#103374][1] I notived a couple of minor
improvements I could make.

/cc @chrisamiller, @tabbott, @jweible

[1]: https://rt.gsc.wustl.edu/Ticket/Display.html?id=103374

### CODE REVIEW

**Comment by jweible** [comment]
+1, much better

**Comment by nnutter** [comment]
@tabbott, I removed the commit that changed the output file which removed your comment (I was testing that rebase still does that because I had reason to believe it no longer did).

**Comment by tabbott** [comment]
+1

**Comment by chrisamiller** [comment]
+1

**Pull request merged**
