### PR TITLE
add option to run on non-succeeded build

### PR DESCRIPTION
**Pull request by chrisamiller**
This is useful when a build crashes in the late stages, preventing create reports from running. Gives us an easy way to at least pull out SNVs and indels without waiting for a rebuild.

### CODE REVIEW

**Comment by tmooney** [comment]
With the name `--force-use-latest-build`, I expected it to use the latest build even if there is an earlier build that Succeeded, while this implementation appears to prefer a Succeeded build.  Maybe it should be something like `--fallback-to-latest-build`?

**Comment by chrisamiller** [comment]
Good suggestion, made that change.

**Comment by tmooney** [comment]
+1 :japanese_castle:

**Comment by brummett** [comment]
+1

**Pull request merged**
