### PR TITLE
Remove "MutationalSignificance" pipeline.

### PR DESCRIPTION
**Pull request by tmooney**
`gmt music` is still around, though!

### CODE REVIEW

**Comment by jasonwalker80** [comment]
+1

**Comment by jasonwalker80** [comment]
@malachig or @chrisamiller any thoughts on this PR to remove MutationalSignificance?  If I recall correctly no one was using the pipeline/model type, but `gmt music` (command tree NOT part of this removal) is occasionally used.

**Comment by chrisamiller** [comment]
It can be dropped. This was a well-intentioned, but ultimately not very successful attempt to automate MuSiC. :-(

**Comment by tmooney** [comment]
I've rebased this to address a conflict in `Define-docs.t` (due to the removal of PhenotypeCorrelation).  If it passes tests I'll start the database cleanup.

**Pull request merged**
