### PR TITLE
InstData Delete CLI

### PR DESCRIPTION
**Pull request by ebelter**
Remove the 'remove' command and use CRUD built in 'delete'. Additionally, update the instrument data property on the delete command to only retrieve imported data.

### CODE REVIEW

**Comment by tmooney** [comment]
+1.

It's interesting that constructing this command programmatically does not enforce the class specification, but it's no different than the old class in that regard!

**Comment by ebelter** [comment]
@tmooney Yeah...I have a test written to make sure that it would enforce the class, but it doesn't. Didn't add it because it didn't prove what I wanted it to.

**Comment by ebelter** [comment]
@tmooney Is this worthy of a changelog?

**Comment by tmooney** [comment]
@ebelter Sounds like a good idea.  I don't think the current remove command is widely used, but perhaps it should be!

**Comment by ebelter** [comment]
@tmooney I got the test to work to ensure only imported insdata is deleted. Review if you'd like.

**Comment by tmooney** [comment]
New test generally looks good.  I think it should enable no-commit to be safe.

**Pull request merged**
