### PR TITLE
Only schedule current dependent reference alignments.

### PR DESCRIPTION
**Pull request by tmooney**
This should eliminate the issue of new microarray data triggering rebuilds of old/outdated models.

### CODE REVIEW

**Comment by acoffman** [comment]
To be sure I understand, we still want this processing to occur for analysis projects that are on hold or still pending correct?

**Comment by tmooney** [comment]
@acoffman Yes, I believe so. (At least... we can't rule it out, since) those two states can both transition into "In Progress".

**Comment by acoffman** [comment]
Cool, that's what I thought, I just wanted to be sure.

+1

**Comment by susannasiebert** [comment]
+1

**Pull request merged**
