### PR TITLE
Rnaseq spawned workflows

### PR DESCRIPTION
**Pull request by davidlmorton**
This PR makes it so that all workflows spawned from an rnaseq model are run with WorkflowBuilder.  WorkflowBuilder is where we honor the environment variable that specifies the workflow be run using PTero.

This PR also adds the ability to view spawned workflows using 'genome process view' or 'genome model build view' commands.  Here is an example of the rnaseq test build, run using PTero:

```
Using libraries at /home/archive/dmorton/genome/lib/perl
'build' may require verification...
Resolving parameter 'build' from command argument 'a0781aaead9541d5966764191830a441'... found 1
=== Build ===
Build ID: a0781aaead9541d5966764191830a441      Build Status: Succeeded
Model ID: 13ba093990d34294b8219ee013f62c4a      Model Name: apipe-test-rnaseq
Run by: apipe-tester                            Processing Profile ID: 2762d4c6c0ed4590bd3424b6c213ed7d
Build Scheduled: 2015-08-03 14:12:09            Build Completed: 2015-08-03 15:24:19

Build Class: Genome::Model::Build::RnaSeq
Software Revision: /gscuser/dmorton/deployments/rnaseq_spawned_workflows/genome/lib/perl/Genome/Site/TGI/SiteLib:/gscuser/dmorton/deployments/rnaseq_spawned_workflows/genome/lib/perl:/gsc/scripts/opt/genome/snapshots/genome-3625/lib/perl:/etc/perl:/usr/local/lib/site_perl
Software Result Test Name(s): "dmorton_ptero_test_wb_2" (11), undef (4)
Data Directory: /gscmnt/gc7005/info/model_data/13ba093990d34294b8219ee013f62c4a/builda0781aaead9541d5966764191830a441

=== Workflow ===
   STAGE     STATUS              STARTED       DURATION  P-INDEX  NAME
          succeeded  2015-08-03T19:11:24       01:11:32           a0781aaead9541d5966764191830a441
 execute  succeeded  2015-08-03T19:11:37       00:16:27           . RnaSeq Alignment
   spawn  succeeded  2015-08-03T19:11:51       00:15:32           . . 7CpxtmkHS2uMxOHcpDZwkw
shortcut  succeeded  2015-08-03T19:11:58       00:00:08           . . . per-lane-tophat index #1
          succeeded  2015-08-03T19:12:08       00:00:00           . . . block
          succeeded  2015-08-03T19:12:09       00:13:50           . . . Alignment Dispatcher for 2891578700 (segment A)
 execute  succeeded  2015-08-03T19:12:30       00:13:24           . . . . per-lane-tophat_2
          succeeded  2015-08-03T19:26:01       00:00:00           . . . converge
 execute  succeeded  2015-08-03T19:26:20       00:00:58           . . . merge_2882744155
 execute  succeeded  2015-08-03T19:29:30       00:00:20           . RnaSeq Alignment Metrics
 execute  succeeded  2015-08-03T19:28:57       00:05:03           . RnaSeq BamQc
   spawn  succeeded  2015-08-03T19:29:33       00:02:41           . . SzCPQrIQTGSCSGxJjdbqrA
 execute  succeeded  2015-08-03T19:30:55       00:00:15           . . . BioSamtools Error Rate
 execute  succeeded  2015-08-03T19:30:36       00:00:23           . . . BioSamtools Read Length Distribution
 execute  succeeded  2015-08-03T19:30:59       00:01:10           . . . Collect Picard G+C Bias
 execute  succeeded  2015-08-03T19:31:04       00:00:14           . . . Collect Picard Metrics
 execute  succeeded  2015-08-03T19:30:34       00:00:29           . . . FastQC Generate Reports
 execute  succeeded  2015-08-03T19:30:42       00:00:12           . . . SamStat Html Report
shortcut  succeeded  2015-08-03T19:28:20       00:00:18           . RnaSeq Coverage
        parallel-by: annotation_reference_transcripts_mode        . RnaSeq Cufflinks Expression
 execute  succeeded  2015-08-03T19:29:38       00:00:33  0        . . RnaSeq Cufflinks Expression
 execute  succeeded  2015-08-03T19:29:43       00:51:28  1        . . RnaSeq Cufflinks Expression
 execute  succeeded  2015-08-03T19:29:41       00:53:13  2        . . RnaSeq Cufflinks Expression
 execute  succeeded  2015-08-03T19:29:19       00:04:03           . RnaSeq Digital Expression Detection
 execute  succeeded  2015-08-03T19:29:27       00:21:17           . RnaSeq Fusion Detection (chimerascan-vrl 0.4.6)
   spawn  succeeded  2015-08-03T19:29:39       00:18:41           . . 17Okva1RRxeRitKrtRrkOQ
shortcut  succeeded  2015-08-03T19:30:26       00:00:16           . . . IndexCommand
 execute  succeeded  2015-08-03T19:31:30       00:14:10           . . . DetectorCommand
 execute  succeeded  2015-08-03T19:46:55       00:00:57           . . . FilterCommand
 execute  succeeded  2015-08-03T19:51:14       00:00:26           . RnaSeq Fusion Detection Annotation
 execute  succeeded  2015-08-03T19:29:29       00:00:42           . RnaSeq Picard Metrics
 execute  succeeded  2015-08-03T19:29:14       00:12:16           . RnaSeq Splice Junction Summary
```

### CODE REVIEW

**Comment by mkiwala** [comment]
The test that is failing is Model_ClinSeq_Command_SummarizeModels_t while trying to diff some Stats.tsv file.

PR #907 is also failing in the same way with the exact same diff, so the problem seems to be unrelated to this PR or PR #907.

+1

**Comment by mkiwala** [comment]
@tmooney points out that I missed another failing test on this PR.

**Comment by davidlmorton** [comment]
There is still some work to be done in order to allow PTero to run workflows that include 'isOptional' inputproperties.  In the interest of keeping this PR small enough to be easily evaluated I'm going to make those changes in a separate PR.  Therefore, PTero (in this PR) is capable of running the rnaseq test build, but not all alignment strategies that are possible to declare.

**Comment by tmooney** [comment]
+1

I have a branch that is mostly updated to convert `Genome::InstrumentData::Composite::Workflow` to use `Genome::WorkflowBuilder`.  It currently fails tests, because previously optional inputs are being treated as required :smile:   Once completed the conversion will overall simplify this code quite a bit!

**Comment by mkiwala** [comment]
+1

**Pull request merged**
