### PR TITLE
Remove alert from `genome disk group available-space` report

### PR DESCRIPTION
**Pull request by tmooney**
I'm migrating this to a Jenkins task, so that will be responsible for alerting if trouble arises.

### CODE REVIEW

**Comment by nnutter** [comment]
Depending on how you want to integrate it you might want it to exit non-zero when it would have previously alerted.

**Comment by tmooney** [comment]
Good idea--I've changed this to exit non-zero if any groups are low on space.

I'm currently using the Text Finder plugin marking it Unstable on low space. It'll be simpler once [this issue](https://issues.jenkins-ci.org/browse/JENKINS-23786) is resolved!

**Comment by nnutter** [comment]
:+1:

**Comment by acoffman** [comment]
+1

**Pull request merged**
