### PR TITLE
missed some defines

### PR DESCRIPTION
**Pull request by ernfrid**
Missed a few additional places where this data should have been tested using defined rather than truth.

### CODE REVIEW

**Comment by brummett** [comment]
Is it really valid for ```$chrom``` or ```$new_chrom``` to be 0 or an empty string?

**Comment by ernfrid** [comment]
Probably not. Same for the stop, it should be an integer.

**Comment by ernfrid** [comment]
Better now @brummett ?

**Comment by gatoravi** [comment]
Unrelated to your changes, but might be a bug, should https://github.com/ernfrid/genome/blob/master/lib/perl/Genome/Model/Build/ReferenceSequence/Converter.pm#L84 check for "lift_over" instead of "liftOver"?

**Comment by ernfrid** [comment]
I think you are correct and have made the change as well as harmonized capitalization on an error message.

**Comment by brummett** [comment]
As you have it now, ```0``` would be an acceptable chromosome; that seems wrong.
Should it be ok if both ```$start``` and ```$stop``` were 0 to denote an insertion?
Is this the place to check that ```$stop``` is freater or equal to ```$start```?

**Comment by ernfrid** [comment]
I can't find any documentation of the BED format that suggests that 0 shouldn't be an allowable string name for a chromosome (though I agree it would be bad form to do so).

I think technically, `$stop` is supposed to be one-based, but I think you are correct in terms of how we utilize this internally so I have changed that.

**Comment by brummett** [comment]
+1

**Comment by apregier** [comment]
+1

**Pull request merged**
