### PR TITLE
Basic refalign QC summary.

### PR DESCRIPTION
**Pull request by jasonwalker80**
Remove the ADSP QC command and make it applicable to all projects.

### CODE REVIEW

**Comment by jasonwalker80** [comment]
Yeah, duplication_rate still is still there.  Number of unique bases would have been calculated from that.  Duplication rate seems to be more commonly used across all projects.

**Comment by ernfrid** [comment]
Yep, very ADSP specific.

____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by tmooney** [comment]
+1.  It'd be nice to have a test that runs the tool.  (That might be easier to create if it wrote a TSV instead of an XLS file.)

**Comment by jasonwalker80** [comment]
The transition from XLS to TSV might be a worthwhile follow up PR to enable tests.  I'm not sure anyone requires the XLS functionality and TSV will open as a spreadsheet.

**Pull request merged**
