### PR TITLE
Use Genome::Utility

### PR DESCRIPTION
**Pull request by gatoravi**
This fixes issues in ClinSeq where the path to the junctions file is currently incorrectly resolved.

### CODE REVIEW

**Comment by tmooney** [comment]
This should `use Genome::Utility::Text;`  The Autoloader doesn't like to load modules via `::` rather than `->` calls.

Otherwise, +1 (assuming tests pass)!

**Comment by gatoravi** [comment]
Sorry I keep forgetting this, I've added this in now.

**Comment by acoffman** [comment]
+1

**Comment by gatoravi** [comment]
If I'm reading this correctly, there's a mixture of RNAseq builds out there, one set where the junctions filenames look like `NCBI-human.ensembl-67_37l_v2*` and another set that looks like `NCBI-human.ensembl_67_37l_v2.` The Genome::Utility method seems to resolve to the latter, the previous perl sub line in ClinSeq used to refer to the former. Any thoughts on how to make this backwords compatible? Should this be handled in Genome::Utility or in ClinSeq?

**Comment by jasonwalker80** [comment]
Can you provide a list or query that demonstrates the mixed behavior?  Was there a specific commit or genome version where this can be traced back to?

**Comment by gatoravi** [comment]
The test failure in this pull-request is due to one such RNA-seq build I think. Yeah I could add a further check in ClinSeq, I just wanted to make sure this is expected.

**Comment by gatoravi** [comment]
Hi sorry for the trouble, this PR will need another round of review since I just pushed a couple of commits to address the test-failures.

**Comment by jasonwalker80** [comment]
+1 given the mixed bag of naming conventions.

**Comment by tmooney** [comment]
+1.

I wonder if it'd be better to try the `Genome::Utility::Text` version first, but it probably is of little consequence.

**Pull request merged**
