### PR TITLE
The param is called "users" not "result_users" in results themselves.

### PR DESCRIPTION
**Pull request by tmooney**
This fixes #1783.

### CODE REVIEW

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by chrisamiller** [comment]
+2, (if the above failing checks aren't an issue)

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Pull request merged**
