### PR TITLE
Common somatic interface to the tumor/normal samples.

### PR DESCRIPTION
**Pull request by jasonwalker80**
This was inspired by resolving a long standing JIRA issue, APIPE-2849.  However, @acoffman  and @susannasiebert  this is a very similar problem to how ClinSeq interfaces with somatic model types.

### CODE REVIEW

**Comment by susannasiebert** [comment]
+1 once tests pass.

**Comment by acoffman** [comment]
+1

**Comment by chrisamiller** [comment]
+1 :last_quarter_moon_with_face:

**Comment by tmooney** [comment]
+1.  If these common accessors are going to be used from within a build process, it would be good to also add them to the build classes.  (Since the samples are resolved via inputs, it is possible that the build being used as an input to the given running build has a different value than the current one on the model.)

**Pull request merged**
