### PR TITLE
AnP Config for InstData: require_user_verify => 0 for instdata

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by tmooney** [comment]
I personally like that this will stop me from accidentally listing over nine thousand instrument data.  But if people find it annoying, then +1 :smile:

**Comment by acoffman** [comment]
+1

**Comment by susannasiebert** [comment]
Just out of curiosity, what's the reasoning behind making this change?

**Comment by ebelter** [comment]
@susannasiebert The default was to require the user to select instrument data. When I use the command, I have already selected the instrument data I am curious about to give to the command. I have not merged it because I have been thinking about Tom's comment. Either way, someone will be annoyed :smile: . Do you have an opinion? [about this]

**Comment by susannasiebert** [comment]
I don't have very strong feelings about this option one way or another but I do think it would be nice to limit listing thousands of instrument data if somehow possible. I'm thinking something along the lines of not requiring user verification if the instrument data was pulled by id but require verification if you use any other property. Not sure if that's possible though and if that would solve your problem.

**Comment by ebelter** [comment]
I am going to close this as it is NBD to filter.

**Pull request closed without merging**
