### PR TITLE
Zero size variants in CreateReport

### PR DESCRIPTION
**Pull request by jasonwalker80**
Allow for zero size variant files in the Create Report step of Somatic Variation models.

### CODE REVIEW

**Comment by jasonwalker80** [comment]
@susannasiebert @acoffman or @tmooney any additional suggestions?

**Comment by tmooney** [comment]
It is usually customary in our pipelines to produce empty files when given an empty input.  (See for example `add_tiers` in this module.)  It might be worthwhile to continue that practice here.

Otherwise, +1.

**Comment by susannasiebert** [comment]
I agree with @tmooney's comment. Otherwise, +1.

**Comment by jasonwalker80** [comment]
Thanks for the suggestions.  A new commit that will touch the expected files rather than skip steps.

**Pull request merged**
