### PR TITLE
Update CLE Test

### PR DESCRIPTION
**Pull request by dufeiyu**
This is an update to the CLE Test and must be approved by the Medical Director of the CLE

### CODE REVIEW

**Comment by tmooney** [comment]
The new process ID appears in the database and points to a succeeded process, so I offer a +1.  I make no claims as to the suitability of the data contained in that process :smile:

**Comment by wschroeder** [comment]
Is `CleTest.t` actually a test of the `Genome::Config::Parser`?  Just wondering because the test mirrors the data in the same commit; it does not include any special comments that one might expect as a reminder to do documentation updates or something.  Also, `Genome/Config/Parser.t` is virtually useless on its own (it just does a syntax check, very much a subset of the functionality in `CleTest.t`), so a test of yaml-to-hashmap does make sense to have.  It is just unclear to me as a newcomer modifying the parser if I was unaware of `Genome/Site/TGI/CleTest.t`.  Maybe the code should be moved into `Genome/Config/Parser.t`?  What should one actually test for `Genome::Site::TGI::CleTest`?  Maybe that a hashmap is returned at all?

**Comment by tmooney** [comment]
`test-tracker` takes care of knowing which tests are applicable to run for a given change.

```
$ test-tracker list Config/Parser.pm
   73  lib/perl/Genome/Model/Command/Services/WebApp/Core.t
   25  lib/perl/Genome/Config/Command/ConfigureQueuedInstrumentData.t
   18  lib/perl/Genome/Model/GenotypeMicroarray.t
   17  lib/perl/Genome/Config/AnalysisProject/Command/AddModel.t
   12  lib/perl/Genome/Sample-add_default_genotype.t
    9  lib/perl/Genome/Model/GenotypeMicroarray-post_success.t
    8  lib/perl/Genome/Model/Command/InstrumentData/Assign/AllCompatible_with_AnalysisProject.t
    7  lib/perl/Genome/Config/AnalysisProject/InstrumentDataBridge.t
    5  lib/perl/Genome/Config/AnalysisProject/Command/ReplaceModel.t
    5  lib/perl/Genome/Test/Factory/AnalysisProject.t
    4  lib/perl/Genome/Config/Profile.t
    3  lib/perl/Genome/Config/Tag/Profile/Item.t
    3  lib/perl/Genome/Config/Parser.t
    3  lib/perl/Genome/Config/Parser/YAML.t
    2  lib/perl/Genome/Qc/Command/Config/AddAndSave.t
    2  lib/perl/Genome/Site/TGI/CleTest.t
    2  lib/perl/Genome/Qc/Config.t
    2  lib/perl/Genome/Config/AnalysisProject/Command/UntagConfigFile.t
    2  lib/perl/Genome/Config/Tag/AnalysisProject/SubjectMapping.t
    2  lib/perl/Genome/Config/AnalysisProject/Command/TagConfigFile.t

Found 20 tests which would take a total of 204 seconds (00:03:24) to run.
```

I believe `Config/Parser/YAML.t` is the general test that applies here.  `Genome::Config::Parser` is an abstract superclass.

I am under the impression this test is the way it is for CLE-specific reasons rather than as a generic test of the Parser (which gets used in several places in Genome).  It was added in #908 to make sure that any changes do not break the CLE regression test configuration.  If it fails, we have to be concerned about it affecting CLE.  Is it a little silly?  Perhaps, but many things about CLE compliance seem to be!

**Comment by dufeiyu** [comment]
For anyone who is interested in this, confluence page below shows the steps how to update CLE_regression test. 
[https://confluence.gsc.wustl.edu/display/CLIA/7206+Releasing+a+new+reference+avatar+%28%27blessed+process%27%29+for+the+CLE+assays](url)

**Comment by jasonwalker80** [comment]
+1

**Pull request merged**
