### PR TITLE
Remove EpitopePrediction batchrun script.

### PR DESCRIPTION
**Pull request by tmooney**
This references volumes that are being eliminated.

### CODE REVIEW

**Comment by wschroeder** [comment]
Was it a temporary script that solved a narrow problem?  Totally unnecessary/unwanted by anyone?  If so, +1

**Comment by tmooney** [comment]
I don't really know who used it or why. I tend to be pretty suspicious of any `.pl`s in the repository!

**Comment by jasonwalker80** [comment]
@jhundal should this be moved to [pVAC-Seq](https://github.com/griffithlab/pVAC-Seq) or can it safely be removed from genome without moving it over?  It appears to be a wrapper around the GMTs we have moved to pVAC-Seq, but perhaps it was unintentionally added to the genome repo.

Regardless, this doesn't belong as-is in genome, +1.

**Comment by jhundal** [comment]
Yes this can be removed. I don't know how it made it to the genome repo!
It was in my personal git repo. 
Sidenote: Did not understand @tmooney 's comment.  Is sata141 being removed?

**Comment by tmooney** [comment]
@jhundal  This one got caught by my search for sata809.  As far as I know, sata141 is safe for now.

**Comment by wschroeder** [comment]
sata141 is marked as belonging to TECHD_SOLEXA... In light of cleanups, I'd be worried about TechD wanting to manage the data there.  ...unless I'm way off base, and jhundal is in TechD! :)

**Comment by jhundal** [comment]
I was in TechD once upon a time, and most of the stuff I have on sata141 is related to TechD projects. But I do need that data accessible.

**Pull request merged**
