### PR TITLE
Delete the tag bridges in advance of deleting the subject mapping.

### PR DESCRIPTION
**Pull request by tmooney**
Otherwise the delete will fail due to the FK constraint.

### CODE REVIEW

**Comment by acoffman** [comment]
+1

**Comment by brummett** [comment]
The whole eval might be better written as
```
foreach my $hangoff_type ( qw( subject_bridges inputs tag_bridges) ) {
    $_->delete foreach $self->$hangoff_type;
}
```

Any idea why the eval is even there?  Right after, it's re-throwing the exception.

**Comment by tmooney** [comment]
@brummett Updated!

I don't know what the `eval` was for. It doesn't seem like it does anything, so I took it out.

**Comment by brummett** [comment]
+1

**Pull request merged**
