### PR TITLE
Bam readcount vcf encoding

### PR DESCRIPTION
**Pull request by davidlmorton**

### CODE REVIEW

**Comment by tmooney** [comment]
+1 :custard:

**Comment by ernfrid** [comment]
I'm in a hurry and merging. This is a simple change.

**Comment by apregier** [comment]
Do we need to set test names on old results?

**Comment by davidlmorton** [comment]
No, this should be a backwards compatible change since there will be no '|' characters to translate back into commas.  If those results are to be used with Joinx though they will need to be recomputed so in that sense it might be warranted.

**Pull request merged**
