### PR TITLE
Add loh tool to clinseq pipeline

### PR DESCRIPTION
**Pull request by kkrysiak**
This pull request is to incorporate identify-loh tool in the ClinSeq pipeline. Produces a folder with basic visualizations of SNPs comparing tumor and normal VAFs on a per chromosome basis.

### CODE REVIEW

**Comment by malachig** [comment]
Hi @kkrysiak and @gatoravi .  This is awesome.  Though at the moment it looks like a test is failing?

**Comment by kkrysiak** [comment]
This is because snvs.1.unfiltered is in the test_inputs folder but not the results. @gatoravi, do you think this is one of the files we should keep? I thought that was one of the files we decided to get rid of for clean up but I could be mistaken.

**Comment by gatoravi** [comment]
CI, test this

**Comment by malachig** [comment]
@gatoravi are we ready to merge this one yet?

**Comment by gatoravi** [comment]
I think it looks good to be merged! Merging.

**Pull request merged**
