### PR TITLE
Add an additional dir to ignored paths.

### PR DESCRIPTION
**Pull request by gatoravi**

### CODE REVIEW

**Comment by tmooney** [comment]
+1, but will grep still match the desired lines if the initial `\\w+/\\w+/(info|test)` is removed from the regex entirely?  As-is, this may be a problem in other environments (e.g. `cle`) if ClinSeq is used in them in the future.

**Comment by gatoravi** [comment]
I guess we were just trying to be a bit more stringent with the match:) Would other environments including `cle` use a separate testing framework? I can definitely remove the check it if so.

**Comment by dufeiyu** [comment]
How about use  grep -vP '^file'  here so we don't need to deal with different build path.

**Comment by dufeiyu** [comment]
CI, test this

**Comment by gatoravi** [comment]
Nice idea, @dufeiyu, updated this.

**Comment by dufeiyu** [comment]
+1  please merge this asap.

**Pull request merged**
