### PR TITLE
Added CustomReport

### PR DESCRIPTION
**Pull request by davidlmorton**
This report lets you specify the header columns in the plan file.

### CODE REVIEW

**Comment by tmooney** [comment]
+1.

Is there a way to specify a list of parameters in the plan? That might be better than splitting on `,`, although if the labels definitely won't contain commas this syntax is probably simpler.

**Comment by davidlmorton** [comment]
There is a way but the order cannot be guaranteed for is_many properties.

**Comment by acoffman** [comment]
+1

Could you use an ARRAY type rather than an is-many property? Don't know if that preserves order or not.

**Comment by davidlmorton** [comment]
It does preserve the order, but then it cannot be persisted in the DB :(

**Comment by acoffman** [comment]
Exciting! Commas it is then :+1:

**Comment by brummett** [comment]
You could keep them ordered if the Header Labels were instances of another class with text and a rank.  Then, they could be ordered by rank and saved in the DB.

**Comment by davidlmorton** [comment]
Apipe-ci says this passes tests.

**Pull request merged**
