### PR TITLE
update parent-dir for locks

### PR DESCRIPTION
**Pull request by gatoravi**
Trying to create a lock on "/" causes a step to fail in https://github.com/genome/gms/issues/181

### CODE REVIEW

**Comment by nnutter** [comment]
This is probably okay because on sGMS there is really only one level of locking since it runs specifically on one host.  However, since the `scope` is like a namespace it's possible that you would run into accidental collisions.

**Comment by gatoravi** [comment]
Would something like `parent_dir => $ENV{GENOME_LOCK_DIR}/unknown` and  `parent_dir => $ENV{GENOME_LOCK_DIR}/tgisan` be better?

**Comment by nnutter** [comment]
> Would something like `parent_dir => $ENV{GENOME_LOCK_DIR}/unknown` and `parent_dir => $ENV{GENOME_LOCK_DIR}/tgisan` i.e subdirectories within the main locking directory be better?

Probably.  You might also want to have the `site` scope go to a `site` subdirectory.

**Comment by gatoravi** [comment]
I've added a commit for the scope specific subdirectories.
PS - this PR is aimed at the sgms branch but we'd like to incorporate the same change into master to minimize divergence.

**Comment by nnutter** [comment]
:+1:

**Comment by gatoravi** [comment]
I think the test-failures are because this is on the SGMS branch. Merging this in so that we can test this.

**Pull request merged**
