### PR TITLE
Fix list evaluation in scalar context.

### PR DESCRIPTION
**Pull request by tmooney**
This is an `is_many` property, so be ready for multiple values!

### CODE REVIEW

**Comment by jasonwalker80** [comment]
+1

**Comment by brummett** [comment]
Is the consumer of this data also prepared for a listref instead of a simple scalar?

**Comment by tmooney** [comment]
@brummett Yes.  This was broken in #1089--the old version always received an array reference directly.  When `intervals` was changed from a subroutine to an `is_many` property, it began returning a list instead of the reference.

**Comment by brummett** [comment]
+1

**Pull request merged**
