### PR TITLE
genome-env-next iteration

### PR DESCRIPTION
**Pull request by nnutter**
Some fixes and improvements for `genome-env-next`.

### CODE REVIEW

**Comment by nnutter** [comment]
Reviewing individual commits probably makes the most sense.

/cc @tabbott

**Comment by nnutter** [comment]
No test coverage for this but it's in "beta" because of that.

**Comment by ebelter** [comment]
+1 Seems reasonable to me, but I am not completely familiar with the code.

**Comment by apregier** [comment]
+1

**Pull request merged**
