### PR TITLE
IGV link

### PR DESCRIPTION
**Pull request by gatoravi**
This PR adds a column to the SNVIndel report, this is a html URL which takes the user to the site of interest within an existing IGV session. Makes things a little easier for manual review. The default port IGV listens to is 60151.

### CODE REVIEW

**Comment by gatoravi** [comment]
this will need an updated clinseq blessed build, generating one now.

**Comment by acoffman** [comment]
Totally personal preference, no need to implement it, but it might be easier in the future to make these sorts of changes if the columns were consolidated somewhere. Something along the lines of this:
````perl
sub columns {
     return qw(
        min_coverage_observed
        max_normal_vaf_observed
        max_tumor_vaf_observed
        variant_source_callers
        variant_source_caller_count
        data_type
        filtered
    );
}
sub header_extension {
    my $self = shift;
    return join "\t", $self->columns();
}

sub line_extension {
    my $self = shift;
    my $data = shift;

    return join("\t", map { $data->{$_} } $self->columns());
}

#in your current code
 my $full_header =  join("\t", $_,  $self->header_extension());
#staple in extra parts as needed
 my $full_line = join("\t", $_, $self->line_extension($variants->{$v});
#staple in extra parts as needed
````
No need to implement it to merge or anything, just a thought!

+1 With a new blessed build.

**Comment by gatoravi** [comment]
Hi @acoffman, this is great, thanks a lot for the input, I've incorporated it in the code.

**Comment by acoffman** [comment]
+1, looks good!

**Comment by tmooney** [comment]
+1 :radio:

**Pull request merged**
