### PR TITLE
Allow evaluation to be re-parsed

### PR DESCRIPTION
**Pull request by apregier**
If the evaluation has already been run and we just want to
get the stats, we don't need to re-run everything, which takes
a while.  Detect this situation if the compare.txt file exists with
size.
The disadvantage here is that if you actually do want to rerun (e.g.
something has changed), it may not do what you expect (it does print
a debug message that results are just being parsed).
Previously, it would crash when trying to create a symlink that
already existed.

### CODE REVIEW

**Comment by indraniel** [comment]
Could a `--force` boolean parameter to be added to forcefully re-run everything if the `compare.txt` file already exists?  That way one could use the option to purposely override things without having to delete the file before re-running evaluate-vcf.

This would be useful if we noticed a corrupt `compare.txt` file.

**Comment by ernfrid** [comment]
I like @indraniel's idea too. We would need to add clean up to the script then though or we will just fail out. I think that's probably outside the scope of this request.

**Comment by tmooney** [comment]
I'd suggest choosing a different name than `--force`, though.  In the past we've run into trouble with it being unclear exactly what would or wouldn't happen when it's specified!

**Comment by apregier** [comment]
I think I'll just merge as-is and next time we run this and need a force-like option we can add it.

**Pull request merged**
