### PR TITLE
Changes to handle either a Workflow::Model or a G::WorkflowBuilder::DAG.

### PR DESCRIPTION
**Pull request by tmooney**
This allows using `WorkflowBuilder` to construct the workflow for a `Build`.

### CODE REVIEW

**Comment by brummett** [comment]
What about changing the method name in one class (or adding a function alias) to match the other?

**Comment by tmooney** [comment]
I've opened genome/tgi-workflow#6 to add `get_xml` to `Workflow::Model`.  My eventual intent is to switch all model types to using `Genome::WorkflowBuilder`, so that'll be the new interface going forward.

I'll update this PR once that is merged.

**Comment by brummett** [comment]
+1

**Comment by acoffman** [comment]
+1

**Pull request merged**
