### PR TITLE
Stop using GENOME_LSF_QUEUE_ALIGNMENT_PROD.

### PR DESCRIPTION
**Pull request by tmooney**
* Since the queues are controlled by environment variables, the user
can select between the multiple alignment queues by controlling their
environment.
* Leave the old environment variable in as non-required for now (so as to
not break everyone's configurations when we deploy the new snapshot).
* As an added bonus if a user `genome model build start`s a production build, it will no longer get stuck in the Workflow server repeatedly trying to `bsub` to a queue the user can't use.

### CODE REVIEW

**Comment by nnutter** [comment]
There are a couple of spots that still mention `GENOME_LSF_QUEUE_ALIGNMENT_PROD`:

```
$ git grep GENOME_LSF_QUEUE_ALIGNMENT_PROD
lib/perl/Genome/Env/GENOME_LSF_QUEUE_ALIGNMENT_PROD.pm:package Genome::Env::GENOME_LSF_QUEUE_ALIGNMENT_PROD;
lib/perl/Genome/Env/GENOME_LSF_QUEUE_ALIGNMENT_PROD.pm:GENOME_LSF_QUEUE_ALIGNMENT_PROD
lib/perl/Genome/Model/Build/DeNovoAssembly/Allpaths.pm:    $queue = $ENV{GENOME_LSF_QUEUE_ALIGNMENT_PROD} if $ENV{UR_DBI_NO_COMMIT};
lib/perl/Genome/Model/Build/DeNovoAssembly/Velvet.t:my $queue = ( $build->run_by eq 'apipe-tester' ) ? $ENV{GENOME_LSF_QUEUE_ALIGNMENT_PROD} : $ENV{GENOME_LSF_QUEUE_BUILD_WORKER_ALT};
lib/perl/Genome/ProcessingProfile/DeNovoAssembly.t:    <operationtype commandClass="Genome::Model::DeNovoAssembly::Build::Assemble" lsfProject="build%s" lsfQueue="$ENV{GENOME_LSF_QUEUE_ALIGNMENT_PROD}" lsfResource="-n 4 -R 'span[hosts=1] select[mem&gt;61440] rusage[mem=61440]' -M 63963136" typeClass="Workflow::OperationType::Command" />
lib/perl/Genome/Site/TGI.pm:        GENOME_LSF_QUEUE_ALIGNMENT_PROD
```

**Comment by tmooney** [comment]
Thanks!  Updated to remove those, too.  (I'm not sure why my `grep` did not catch them but yours did!)

**Comment by nnutter** [comment]
:+1: if tests pass.

**Comment by acoffman** [comment]
+1

**Pull request merged**
