### PR TITLE
clinseq: update defaults in update-analysis

### PR DESCRIPTION
**Pull request by gatoravi**
Update the default annotation-build, dbsnp version, cancer-annotation db and ref-align processing-profile used by ClinSeq/UpdateAnalysis.

### CODE REVIEW

**Comment by nnutter** [comment]
I suspect this needs input metadata added to the test database; see [Test Database Template](https://confluence.gsc.wustl.edu/display/APIPE/Test+Database+Template) for that process.  Please get some help from APIPE if needed.

**Comment by malachig** [comment]
Hey @gatoravi, can you also update the default RNA-seq PP in `update-analysis` to `December 2014 Firststrand RNA-seq Candidate 1 (7381e45615374670877a4e16c97b4908)`

**Comment by nnutter** [comment]
It looks like updating the test DB snapshot also pulled in a rename:

WGS Testing - Blue Pippin Size Selection Variation <f5593bdfc0aa432b84e2bbdcc30c1c76>
November 2014 Reference Alignment Candidate 1 <f5593bdfc0aa432b84e2bbdcc30c1c76>

**Comment by gatoravi** [comment]
thanks for looking at this, I've been trying to resolve the test failure but I'm not sure I follow whats going on here. 
The expected output [here](https://github.com/gatoravi/genome/blob/d383602e592229465ccda1c09b13614fc76d789f/lib/perl/Genome/Model/ClinSeq/Command/TestGenomeCommands.t.d/genome-model-clin-seq-update-analysis.err) looks right. "November 2014 Reference Alignment Candidate 1" is the correct expected output.  When I run `genome processing-profile list reference-alignment --filter id=f5593bdfc0aa432b84e2bbdcc30c1c76` this is the name that I see there as well. Not sure where the "Blue Pippin .." is coming from.

**Comment by nnutter** [comment]
If the name in *production* is correct then you need to carry it over to the *test DB snapshot*.

```
$ genome processing-profile list reference-alignment --filter id=f5593bdfc0aa432b84e2bbdcc30c1c76 --show name --noheaders
November 2014 Reference Alignment Candidate 1

$ genome-env genome processing-profile list reference-alignment --filter id=f5593bdfc0aa432b84e2bbdcc30c1c76 --show name --noheaders
...
WGS Testing - Blue Pippin Size Selection Variation
```

You may be able to do this by running the two tests using the technique previously linked to transfer the data from production to the test DB snapshot.

**Comment by gatoravi** [comment]
ok, looks like the tests passed! any comments?

**Comment by apregier** [comment]
+1

**Comment by nnutter** [comment]
:+1:

**Pull request merged**
