### PR TITLE
Remove ClinSeq OriginalScripts Directory

### PR DESCRIPTION
**Pull request by tmooney**
These have been hanging out for awhile; a test for one started failing, so I propose removing them rather than fixing the failed test.

### CODE REVIEW

**Comment by gatoravi** [comment]
I'm ok with this change, I've put this folder [here](https://github.com/griffithlab/misc-resources/tree/master/OriginalClinSeqScripts) just in case anyone's looking for it down the road.

**Comment by susannasiebert** [comment]
+1. 🍰  for deleting almost 10k loc.

**Comment by jeldred** [comment]
+10k

**Comment by tmooney** [comment]
These scripts will also remain available in the git history here.

**Comment by malachig** [comment]
+1

**Pull request merged**
