### PR TITLE
Use parens around list

### PR DESCRIPTION
**Pull request by tmooney**
(Perl 5.14+ doesn't like a bare qw().)

### CODE REVIEW

**Comment by susannasiebert** [comment]
Should we change/fix this everywhere in our code base?

**Comment by tmooney** [comment]
Yes!  I'm surprised it's as common a pattern as it is.

**Comment by brummett** [comment]
[Here is the explanation](http://docs.activestate.com/activeperl/5.14/lib/pods/perl5140delta.html#use_of_qw______as_parentheses) for the change.  The parens where always supposed to be there, but ```qw()``` tricked a bug in the parser.

**Comment by brummett** [comment]
+1

**Comment by acoffman** [comment]
+1

**Comment by iferguson90** [comment]
+1 :cow:

**Pull request merged**
