### PR TITLE
Add build38 options for downloading SV annotation files.

### PR DESCRIPTION
**Pull request by jasonwalker80**
Add build38 options for downloading SV annotation files.

### CODE REVIEW

**Comment by tmooney** [comment]
+1; I didn't check that the chosen sort columns are the right ones, but if they are this looks like it'll use them!

**Comment by jasonwalker80** [comment]
@gatoravi could you take a look at this PR for the SV annotation issue.

**Comment by gatoravi** [comment]
+1
I verified this works by running ` genome db ucsc gap-list  --filename=/tmp/gaplist.csv --reference-name=hg18` this seems to work well. However when I try `genome db ucsc gap-list  --filename=/tmp/gaplist.csv --reference-name=hg38` it seems to result in an empty file and a `ERROR: Empty file passed to sort.`, I hope this is expected.
Also, just as a note to self, the sort columns are different for the `gaplist` module since this module does not request the `bin` column like the other two.

**Comment by jasonwalker80** [comment]
I pushed a commit to add the hg38 table name for the gap-list command.  Nice catch.

**Comment by gatoravi** [comment]
Yeah the `gap-list` command works well now! 👍

**Pull request merged**
