### PR TITLE
Use UR roles in Genome

### PR DESCRIPTION
**Pull request by brummett**
This branch contains changes that move several classes to be UR Roles instead of abstract parent classes.

The branch can't be tested or merged until after https://github.com/genome/UR/pull/63 is merged.

### CODE REVIEW

**Comment by ebelter** [comment]
+1 A lot to look at here, but seems good. Great job! I am sure it was tedious.

**Comment by brummett** [comment]
CI, test this

**Comment by brummett** [comment]
Looks like Genome::SoftwareResult::ParamInputFactory is another candidate for the Role treatment

**Comment by brummett** [comment]
Needs genome/UR#109 and genome/UR#110

**Comment by brummett** [comment]
CI, test this

**Comment by brummett** [comment]
CI, test this

**Comment by acoffman** [comment]
+1 this looks awesome!

**Pull request merged**
