### PR TITLE
More annotation structure updates to biotype map.

### PR DESCRIPTION
**Pull request by jasonwalker80**
Several new gene biotypes added to the AnnotationStructures biotype class map.

### CODE REVIEW

**Comment by jasonwalker80** [comment]
New commit to include changes from #951 which where accidentally merged and reverted in #955 .  All to avoid merge conflicts.

**Comment by tmooney** [comment]
+1, as best I can tell these match [the docs](http://www.gencodegenes.org/gencode_biotypes.html)!

The existing `ncrna` list is alphabetized (albeit with capitals sorted before minuscules).  It might be preferable to keep them ordered.

**Comment by jasonwalker80** [comment]
alphabetical order added.  need one more +1 and tests to pass.

**Comment by apregier** [comment]
+1

**Pull request merged**
