### PR TITLE
InstData Import: allow the specification of working directory

### PR DESCRIPTION
**Pull request by ebelter**
This will overcome the problem of not having enough local (tmp) disk space to process files for import.

### CODE REVIEW

**Comment by ebelter** [comment]
This is to allow the importing of really large BAMs. Latest request was from @rlesurf. Take a look  @jasonwalker80?

**Comment by tmooney** [comment]
+1 🍬

**Comment by jasonwalker80** [comment]
+1

**Comment by rlesurf** [comment]
I can confirm that the code changes worked for me. Only 2 WGS BAMs that are still importing. Thanks Eddie!

**Pull request merged**
