### PR TITLE
TCGA Priorities: Add dump_vcfs option to create sdrf file only

### PR DESCRIPTION
**Pull request by dufeiyu**
Refer to https://jira.gsc.wustl.edu/browse/APIPE-3339. There is need to create sdrf file without time consuming vcf dump. This needs early merge.

### CODE REVIEW

**Comment by dufeiyu** [comment]
@apregier  Can you review this ? Thanks.

**Comment by dufeiyu** [comment]
@tmooney  Can you review this ? thanks.

**Comment by apregier** [comment]
+1 Looks ok to me - I assume Mike knows what he is talking about with the SDRF file changes and they will pass the validator...

**Comment by tmooney** [comment]
+1, this looks like it gets the job done!

I might have made a separate PR for the changes inside `gmt tcga sdrf` as they don't seem connected to this new `dump_vcfs` option.  I overheard the request for those, so I'll assume they're fine :smile:

**Pull request merged**
