### PR TITLE
CHANGELOG: bump clin-seq blessed build

### PR DESCRIPTION
**Pull request by ebelter**

### CODE REVIEW

**Comment by ebelter** [comment]
@gatoravi New clin-seq blessed build.

**Comment by ebelter** [comment]
No tests to run, so the quick-tests is failing.

**Comment by gatoravi** [comment]
+2 I assume this is because of https://github.com/genome/genome/pull/720

**Comment by ebelter** [comment]
Yep. I think @jasonwalker80 wants to take a closer look at why these files were not present in the previous build.

**Comment by jasonwalker80** [comment]
+1

**Pull request merged**
