### PR TITLE
convert a couple more values to configuration

### PR DESCRIPTION
**Pull request by nnutter**

### CODE REVIEW

**Comment by nnutter** [comment]
CI, test this.

**Comment by davidlmorton** [comment]
Was the change from 1280 to 1024 intentional?

**Comment by nnutter** [comment]
Yes, for us, it's still configured to be 1280 but I changed the default to 1024 because the original `syslog` has a 1KB limit.  Even 1024 might be too big depending on the formatting of the output but it seems less wrong than 1280 as a default.

**Comment by davidlmorton** [comment]
+1

**Comment by tmooney** [comment]
+1, I'd be tempted to rename the configuration variable to `max_syslog_message_length`.

**Pull request merged**
