### PR TITLE
Recognize new date format

### PR DESCRIPTION
**Pull request by mkiwala**
Capturing this new date format seems more desirable than changing how
the logs are created for two reasons:
1) changing how the logs are created would require re-packaging and
re-deploying Flow
2) updating the recognizer to allow this date format allows us to
automatically determine historical errors

### CODE REVIEW

**Comment by nnutter** [comment]
:+1: I think that 2) is sufficient and that 1) is probably not.

**Comment by brummett** [comment]
Does ```$FLOW_DATE``` need to get added to ```$EXCEPTION_FINDING_REGEX``` also?

**Comment by mkiwala** [comment]
The `$EXCEPTION_FINDING_REGEX` appears to be tailored to Perl exceptions.  I think we'd have to do something different for python exceptions.

**Comment by brummett** [comment]
The date part of each line is added by a log annotator.  In the old Workflow code, it was added by annotate-log.  I'm not sure how the dates get there in Ptero.

**Comment by mkiwala** [comment]
@brummett -- Looks like [this](https://github.com/genome/flow-workflow/blob/52b2c5c3ba1b3f54c2b74f89ebe2a3dc83776653/bin/workflow-wrapper.pl#l24) could be the place.

**Comment by brummett** [comment]
If that style date can ever appear before an exception, then ```$FLOW_DATE``` would need to be added to ```$EXCEPTION_FINDING_REGEX```

**Comment by mkiwala** [comment]
@brummett -- I agree.  I added `$FLOW_DATE` to `$EXCEPTION_FINDING_REGEX`.

**Comment by brummett** [comment]
+1

**Comment by iferguson90** [comment]
+1 :sheep:

**Comment by nnutter** [comment]
CI, test this.

**Pull request merged**
