### PR TITLE
remove duplication in Genome::Role::Logger

### PR DESCRIPTION
**Pull request by nnutter**

### CODE REVIEW

**Comment by nnutter** [comment]
@ebelter, this will conflict with the change you are working on.  If you want you can merge first and I'll rebase.

**Comment by nnutter** [comment]
@ebelter, now I see you merged already genome/genome#759.  I'll rebase!

**Comment by nnutter** [comment]
Nevermind, I'm going crazy... time to go home.

**Comment by ebelter** [comment]
+1

**Pull request merged**
