### PR TITLE
convert to scoped lock

### PR DESCRIPTION
**Pull request by nnutter**
I'll need to deploy this with `gsc-scripts` once merged.

### CODE REVIEW

**Comment by tmooney** [comment]
+1 :eyeglasses:

**Comment by brummett** [comment]
+1 :triangular_ruler:

**Comment by nnutter** [comment]
```
$ ssh apipe-ci.gsc.wustl.edu
$ cd ~/genome/master/
$ gsc-scripts genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl
gsc-scripts gcsearch_load_from_mailman.pl : enter message to software-announce@watson.wustl.edu (Ctrl-D when finished)
update for change in lock API
gsc-scripts: you do not own /gsc/scripts/bin/gcsearch_load_from_mailman, continue? (y/n) [n] y
gsc-scripts: /gsc/scripts/bin/gcsearch_load_from_mailman exists, overwrite? (y/n) [y] y
```

**Comment by nnutter** [comment]
I had to manually fix the hashbang, `gsc-scripts` wouldn't deploy it unchanged and broke it when it changed it.

```
$ head -n 1 /gsc/scripts/bin/gcsearch_load_from_mailman 
#!/usr/bin/env genome-perl
```

```
$ gsc-scripts genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl
gsc-scripts: file genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl has wrong perl, correct it? (y/n) [y] n
gsc-scripts: WARNING: App::Exit: 146: gsc-scripts: genome-webserver/solr/scripts/gcsearch_load_from_mailman.pl has wrong perl, skipping at /gsc/scripts/bin/gsc-scripts line 711, <STDIN> line 1.
```

```
$ /gsc/scripts/bin/gcsearch_load_from_mailman                                                                                                                                                               
Can't open perl script "genome-perl": No such file or directory
```

**Pull request merged**
