### PR TITLE
Script to set up the fill_db environment in which you can pull in obj…

### PR DESCRIPTION
**Pull request by apregier**
…ects from the production db into a test db

### CODE REVIEW

**Comment by tmooney** [comment]
+1.  It'd be nice if there were a better way to get back to the defaults than mixing `genome config` commands with environment variables, but I'm not sure what that would be.

**Comment by apregier** [comment]
Maybe if there were a 'genome config set-default' or 'genome config unset' command?  I'm not sure if either of those would make sense.  I got the idea for doing it this way from Tony's new command to clean up test-db allocations on the filesystem, so if we come up with something it could be used there as well.

**Comment by apregier** [comment]
Thanks, good catch - updated

**Comment by brummett** [comment]
+1

**Comment by tmooney** [comment]
We could make a `genome config get-default` command (using `Genome::Config::default_value`) whose output can be passed to `genome config set-env`.  A `genome config unset-env` command would work well, too.

**Pull request merged**
