### PR TITLE
fix test failure on master due to missing use

### PR DESCRIPTION
**Pull request by nnutter**

### CODE REVIEW

**Comment by dufeiyu** [comment]
+1

**Comment by nnutter** [comment]
For posterity, the tests passed on the genome/genome#663 because `Genome::InstrumentData::AlignmentResult` depends on `Genome::Model::Build::ReferenceSequence` which was loading `Genome::Sys::LockMigrationProxy` prior to genome/genome#667.

**Comment by dufeiyu** [comment]
My bad, missed this in PR#663

**Comment by nnutter** [comment]
@dufeiyu, It's understandable; Perl doesn't make it easy to catch.

**Comment by nnutter** [comment]
Merging early.

**Pull request merged**
