### PR TITLE
WorkflowBuilder class for Block operations.

### PR DESCRIPTION
**Pull request by tmooney**
The "gene-prediction eukaryotic" pipeline was broken by the switchover to `WorkflowBuilder` for all build validation.  This is one step towards making it work again.

### CODE REVIEW

**Comment by ebelter** [comment]
+1

**Comment by acoffman** [comment]
+1

**Comment by davidlmorton** [comment]
I had already done this, but didn't make the PR yet, please review this instead...

https://github.com/genome/genome/pull/858

**Comment by tmooney** [comment]
I've merged the Ptero-related methods from #858 into this.

**Comment by davidlmorton** [comment]
+1

**Pull request merged**
