### PR TITLE
Define _disk_usage_result_subclass_names for refseq builds.

### PR DESCRIPTION
**Pull request by tmooney**

### CODE REVIEW

**Comment by chrisamiller** [comment]
+1

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test FAILed.

**Comment by apipe-tester** [comment]
Merged build finished. Test PASSed.

**Comment by kkrysiak** [comment]
+1

**Pull request merged**
