### PR TITLE
Make GATK Base more like Picard Base

### PR DESCRIPTION
**Pull request by tmooney**
* GATK Base will now build the command lines and execute them, so logic to do this need not be duplicated in each subcommand.
* A few legacy tools (`GermlineIndel`, `GermlineIndelUnifiedGenotyper`, and `SomaticIndel`) are not updated in this PR.  They don't work with recent versions of GATK, anyway.

### CODE REVIEW

**Comment by brummett** [comment]
+1

This is a pretty slick way of managing the command-line params

**Comment by ebelter** [comment]
The tests checking the command have been removed, and there is no testing of command building added to Base.t I like what is done here, but would like some testing around these methods in the base class.

**Comment by tmooney** [comment]
@ebelter I've added a test for the Base class!

**Comment by ebelter** [comment]
+1

**Pull request merged**
