### PR TITLE
Fix gmt picard typos; remove duplicate method

### PR DESCRIPTION
**Pull request by tmooney**

### CODE REVIEW

**Comment by susannasiebert** [comment]
I haven't totally confirmed this but parse_file_into_metrics_hashref and parse_file_into_histogram_hashref seem to be almost identical. Maybe we should attempt some deduplication.

**Comment by tmooney** [comment]
I've removed the second one altogether.  It wasn't called anywhere and--as noted--was almost identical to the first one.

**Comment by susannasiebert** [comment]
+1

**Comment by nnutter** [comment]
:+1:

**Pull request merged**
