### PR TITLE
Production No Longer Hardcoded to "apipe-builder".

### PR DESCRIPTION
**Pull request by tmooney**
Now there's a `Genome::Sys::User::Role` named `production` when deciding to act.

* The default user for new `production` projects has been changed to `prod-builder`.
* `apipe-builder` remains the user with the power to manipulate others' builds.
* The old heuristic for LIMS to find non-project-based data (in `Genome::InstrumentData::Solexa`) is explicitly not being updated.

### CODE REVIEW

**Comment by wschroeder** [comment]
The same algorithm comes up several times:

    my $run_as_user = Genome::Sys::User->get(username => $self->run_as);
    if($run_as_user && $run_as_user->has_role_by_name('production')) {

We should be able to convert any

    my $temp_var = process1();
    # more processing
    if ($condition_based_on_temp_vars($temp_var, ...)) {


to

    if (complex_condition_function_is_true()) {


In this case, to reduce the repetition and extra lines of code, I propose:

    if (Genome::Sys::User->has_role_by_name($self->run_as, 'production')) {

**Comment by tmooney** [comment]
I very nearly did that originally, but by creating`Genome::Sys->user_has_role` since there's an existing `Genome::Sys->current_user_has_role`.  I'll make that change.

(I could also see a good argument that most of the user-related subroutines in `Genome::Sys` should be moved down into `Genome::Sys::User`.  But that'd be a change for a different PR :smile:)

**Comment by acoffman** [comment]
+1

**Comment by brummett** [comment]
+1

**Pull request merged**
